### ISSUE TITLE
batch URLS posible?

### ISSUE THREAD

**Issue by Devicetron** [ChrisYangTW/HelpMeDownload#2]
is there a way I can feed a list of model urls, I have many loras and it's taking days to get the images of my most used ones... 

also it is possible to get the user generated images in the model page?

**Comment by ChrisYangTW** [comment]
Because the initial purpose was to fetch the images provided by the author of a single model, I didn't consider handling multiple models in bulk at once. In future updates, I will consider adding a batch download feature.

For well-known models, the number of user-generated images often exceeds hundreds, and their quality varies. If I were to implement this functionality, I would likely create a separate project dedicated to downloading these images.

**Comment by Devicetron** [comment]
that is a great idea, so many beautiful images and their respective prompts are getting deleted everyday, the separate project you have in mind would be very very cool!

**Comment by ChrisYangTW** [comment]
Implement batch download functionality.  [#183b329](https://github.com/ChrisYangTW/HelpMeDownload/commit/183b329dc401f5c8206269dbc10f580b9377592c) 

Regarding the part of retrieving user-generated images on the model page, I will consider creating a separate project (still thinking about which filtering criteria to set).
